### ISSUE TITLE
Agc增益失败

### ISSUE THREAD

**Issue by Darksiderlyd** [hughcoder/AudioFun#1]
private long mNsxId = 0;
private int mNum_bands = 1;
private long mAgcId;

mAgcId = WebRtcAGCUtils.WebRtcAgc_Create();
int agcInit = WebRtcAGCUtils.WebRtcAgc_Init(mAgcId, 0, 255, 3, 32000);
int agcSetConfig = WebRtcAGCUtils.agcSetConfig(mAgcId, (short) 3, (short) 20, true);
int ret = WebRtcAGCUtils.agcProcess(mAgcId, nsProcessData, mNum_bands, 320, outAgcData, 0, 0, 0, false);

 if (ret != 0) {
     Log.e(TAG, "agcProcess 出问题");
}
这个地方ret一直不为0。参数基本是按您给的配置的。

**Comment by Darksiderlyd** [comment]
你好我把 int ret = WebRtcAGCUtils.agcProcess(mAgcId, nsProcessData, mNum_bands, 320, outAgcData, 0, 0, 0, false);
中的320修改为160 就可以了 这个和采样率有关系吗 只有 8k 和 16k的才可以成功增益吗？

**Comment by hughcoder** [comment]
Hi,你好 ，音频增益是支持32000的

`   // determine number of samples per ms
    if (FS == 8000) {
        L = 8;
        L2 = 3;
    } else if (FS == 16000 || FS == 32000 || FS == 48000) {
        L = 16;
        L2 = 4;
    } else {
        return -1;
    }
`
确保和操作音频文件的采样率保持一致

**Comment by Darksiderlyd** [comment]
谢谢大佬
